I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 221, in script
    Elio "Its good!"
Exception: Sayer 'Elio' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 221, in script
    Elio "Its good!"
  File "C:\Users\Elio Berberi\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Elio Berberi\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Elio' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
marsy 1.01
Mon Dec 11 19:06:52 2023
