I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/homeMenu.rpy", line 15, in script
    $ endOdds()
ScriptError: could not find label 'part6'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\andre\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\andre\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\andre\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\andre\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/homeMenu.rpy", line 15, in script
    $ endOdds()
  File "C:\Users\andre\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'part6'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
marsy 1.01
Mon Dec 11 12:22:25 2023
